ARDUINO_DIR = $(HOME)/.arduino_ide
ARDUINO_LIBS = Ethernet SPI Arduino-Websocket json-streaming-parser steemduino arduino-ht1632c
ARDMK_DIR = $(HOME)/.arduino_mk
BOARD_TAG = mega
BOARD_SUB = atmega2560

include $(ARDMK_DIR)/Arduino.mk
